### ISSUE TITLE
The About page's coffee cup is a bad UX on Android/mobile

### ISSUE THREAD

**Issue by ArtskydJ** [KayserCommentaryOrg/biblicalblueprints.org#17]
![Screenshot_20201206-163044](https://user-images.githubusercontent.com/1833684/101295185-b217b700-37e1-11eb-8f41-bcd9acb6500c.png)

I saw a pop-up about clicking a coffee cup, then didn't see the coffee cup. It's off the right side of the screen on my device. And when I scroll up, it falls off the page, which might be purposeful.

And the text only fills 2/3rds of the screen or so, but that's more preference...

**Comment by saibotsivad** [comment]
Looks like that widget isn't on the page anymore, and the page renders okay on mobile now. (The top navbar is not super great, but that's another issue...)
